%CALLBYMAIN = true;
 dataset = 'spx';
% dataset = 'nky';
% dataset = 'dax';
% dataset = 'ukx';
% dataset = 'eurusd';
% dataset = 'gbpusd';
% datset = 'jpyusd';
backtestPeriod = '01/01/2007::12/31/2011';
%backtest;
